---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/project
  label: Project
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: content/targets
  label: Targets
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: Roadmap
  label: Roadmap
  create: documents
  match: "*"
  new_doc_ext: yml
- type: directory
  path: content/team
  label: Team
  create: none
  match: "*"
- type: directory
  path: content/contact
  label: Contact
  create: none
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
